name: spreadsheet_decoder
description: Spreadsheet files decoder
version: 1.0.2
authors:
- Stéphane Este-Gracias <sestegra@gmail.com>
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  xml:

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0
